# https://www.kernix.com/blog/an-efficient-recommender-system-based-on-graph-database_p9

In [99]:
import pandas as pd
import numpy as np
import matplotlib as plt
from tqdm import tqdm
from py2neo import Graph
import time
%matplotlib inline

In [2]:
graph = Graph('http://neo4j:neo4j@localhost:7474/db/data/', auth=("neo4j", "saveme"))

In [3]:
triplets = pd.read_csv('../data/processed/2015-01-01/triplets.csv')

In [4]:
triplets.head()

,user_id,user_name,event_type,repo_id,repo_name
0,9152315,davidjhulse,PushEvent,28635890,davidjhulse/davesbingrewardsbot
1,5581438,jmoon018,PushEvent,26392647,jmoon018/rshell-unit-tester
2,6352424,christoferpeterson,CreateEvent,28677542,christoferpeterson/Vadek
3,66577,JakeWharton,PushEvent,5152285,square/okhttp
4,9221683,git4ruby,PushEvent,28520835,git4ruby/movie_review1

In [75]:
triplets[triplets.user_id == 100]

,user_id,user_name,event_type,repo_id,repo_name
112498,100,willcodeforfoo,WatchEvent,6761380,vitalets/x-editable
120832,100,willcodeforfoo,IssuesEvent,28639477,servesimple/servesimple
120834,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple
132081,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple
133709,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple
136178,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple
159344,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple
161029,100,willcodeforfoo,PushEvent,28639477,servesimple/servesimple

In [76]:
triplets[triplets.repo_id == 6761380]

,user_id,user_name,event_type,repo_id,repo_name
44079,1169532,rajeshmeniya,WatchEvent,6761380,vitalets/x-editable
89259,6705413,CapitalEffe,IssuesEvent,6761380,vitalets/x-editable
93702,6705413,CapitalEffe,IssueCommentEvent,6761380,vitalets/x-editable
98585,6705413,CapitalEffe,IssuesEvent,6761380,vitalets/x-editable
98586,6705413,CapitalEffe,IssueCommentEvent,6761380,vitalets/x-editable
99158,6705413,CapitalEffe,IssuesEvent,6761380,vitalets/x-editable
102273,426400,altmer,WatchEvent,6761380,vitalets/x-editable
112498,100,willcodeforfoo,WatchEvent,6761380,vitalets/x-editable
204108,9022239,comxd,WatchEvent,6761380,vitalets/x-editable
205213,9022239,comxd,WatchEvent,6761380,vitalets/x-editable

In [90]:
triplets[triplets['repo_name'].str.contains('scikit')]

,user_id,user_name,event_type,repo_id,repo_name
7651,3696068,kittipatkampa,ForkEvent,843222,scikit-learn/scikit-learn
9488,4193054,KatherineMichel,ForkEvent,10518207,IssamLaradji/scikit-learn
15445,78827,jnothman,IssueCommentEvent,843222,scikit-learn/scikit-learn
15520,78827,jnothman,PullRequestReviewCommentEvent,843222,scikit-learn/scikit-learn
15604,78827,jnothman,IssueCommentEvent,843222,scikit-learn/scikit-learn
...,...,...,...,...,...
212424,9487348,ragv,PushEvent,26038110,ragv/scikit-learn
212603,9487348,ragv,PushEvent,26038110,ragv/scikit-learn
212930,9487348,ragv,PushEvent,26038110,ragv/scikit-learn
213782,2354108,coveralls,IssueCommentEvent,843222,scikit-learn/scikit-learn
214950,3793823,biwa7636,WatchEvent,843222,scikit-learn/scikit-learn

In [72]:
triplets[triplets.event_type == 'WatchEvent'].groupby(['user_id'])['user_id'].count()

user_id
100         1
118         1
137         1
160         5
185         1
           ..
10367163    1
10367166    1
10367239    1
10367292    1
10367421    1
Name: user_id, Length: 12548, dtype: int64

In [68]:
triplets[triplets.user_id == 7576559]

,user_id,user_name,event_type,repo_id,repo_name
50853,7576559,wakaryry,WatchEvent,4920442,congmo/jQuery-Tags-Input
51437,7576559,wakaryry,WatchEvent,11534941,TimSchlechter/bootstrap-tagsinput
51675,7576559,wakaryry,WatchEvent,1606665,xoxco/jQuery-Tags-Input
51781,7576559,wakaryry,WatchEvent,11686981,sliptree/bootstrap-tokenfield
59662,7576559,wakaryry,WatchEvent,2715671,fancyapps/fancyBox
...,...,...,...,...,...
73165,7576559,wakaryry,WatchEvent,1211978,metafizzy/isotope
73172,7576559,wakaryry,WatchEvent,1308789,javve/list.js
73180,7576559,wakaryry,WatchEvent,9775802,patrickkunka/mixitup
73181,7576559,wakaryry,WatchEvent,3598373,square/crossfilter
73344,7576559,wakaryry,WatchEvent,5435483,Schepp/CSS-Filters-Polyfill

In [5]:
users = pd.read_csv('../data/processed/2015-01-01/users.csv')

In [6]:
users.head()

,user_id,user_name,CheckRunEvent,CheckSuiteEvent,CommitCommentEvent,ContentReferenceEvent,CreateEvent,DeleteEvent,DeployKeyEvent,DeploymentEvent,...,RepositoryDispatchEvent,RepositoryEvent,RepositoryImportEvent,RepositoryVulnerabilityAlertEvent,SecurityAdvisoryEvent,StarEvent,StatusEvent,TeamEvent,TeamAddEvent,WatchEvent
0,7.0,evanphx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,78.0,indirect,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100.0,willcodeforfoo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,118.0,peterc,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,129.0,canadaduane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
repos = pd.read_csv('../data/processed/2015-01-01/repos.csv')

In [8]:
repos.head()

,repo_id,repo_name,CheckRunEvent,CheckSuiteEvent,CommitCommentEvent,ContentReferenceEvent,CreateEvent,DeleteEvent,DeployKeyEvent,DeploymentEvent,...,RepositoryDispatchEvent,RepositoryEvent,RepositoryImportEvent,RepositoryVulnerabilityAlertEvent,SecurityAdvisoryEvent,StarEvent,StatusEvent,TeamEvent,TeamAddEvent,WatchEvent
0,27,rubinius/rubinius,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
1,28,mojombo/god,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,68,macournoyer/thin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,144,mojombo/chronic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,426,haml/haml,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
#### Create the user, repo nodes and edges between them
# "MERGE" request : creates a new node if it does not exist already

tx = graph.begin(autocommit=False)

user_statement = "MERGE (a:`User`{user_id:{A}, user_name:{B}}) RETURN a"
for i, row in tqdm(users.iterrows(), total = len(users)):
    tx.run(user_statement, {"A": row['user_id'], "B": row['user_name']})
tx.commit()

In [11]:
tx = graph.begin(autocommit=False)

repo_statement = "MERGE (a:`Repo`{repo_id:{A}, repo_name:{B}}) RETURN a"
for i, row in tqdm(repos.iterrows(), total = len(repos)):
    tx.run(repo_statement, {"A": row['repo_id'], "B": row['repo_name']})
tx.commit()

100%|██████████| 66475/66475 [45:21<00:00, 24.43it/s]

In [17]:
tx = graph.begin(autocommit=False)

edge_statement1 = ("MATCH (u:`User`{user_id:{A}}) "
                     "MATCH (r:`Repo`{repo_id:{B}}) MERGE (u)-[e:`")
edge_statement2 =  "`]->(r) RETURN e"
for i, row in tqdm(triplets.iterrows(), total = len(triplets)) :
    edge_statement = edge_statement1 + row['event_type'] + edge_statement2
    tx.run(edge_statement, {"A": row['user_id'], "B": row['repo_id']})
    if i % 200 == 0:
        tx.process()
tx.commit()

100%|██████████| 218939/218939 [06:59<00:00, 522.12it/s]

In [16]:
graph.run('CREATE INDEX ON :User(user_id)')
graph.run('CREATE INDEX ON :Repo(repo_id)')

In [96]:
user_id = 100
threshold = 0.5

# In Strategy 1, the similarity between two users u1 and u2 is the proportion of starred repos they have in common
# The score of one given movie m is the proportion of users similar to u1 who rated m

query = (### Similarity normalization : count number of repos starred by u1 ###
  # Count movies rated by u1 as countm
  'MATCH (u1:`User` {user_id:{user_id}})-[:`WatchEvent`]->(r1:`Repo`) '
  'WITH count(r1) as count1 '
  ### Score normalization : count number of users who are considered similar to u1 ###
  # Retrieve all users u2 who share at least one starred repo with u1
  'MATCH (u1:`User` {user_id:{user_id}})-[:`WatchEvent`]->(r1:`Repo`) '
  'MATCH (r1)<-[w:`WatchEvent`]-(u2:`User`) '
  'WHERE NOT u2=u1 '
  # Compute similarity
  'WITH u2, count1, tofloat(count(w)) / count1 as sim '
  # Keep users u2 whose similarity with u1 is above some threshold
#   'WHERE sim>{threshold} '
  # Compute score and return the list of suggestions ordered by score
  'RETURN DISTINCT u2.user_name, sim ORDER BY sim DESC ')
  
tx = graph.begin()
result = tx.run(query, {'user_id': user_id, 'threshold': threshold}).data()
result

[{'u2.user_name': 'comxd', 'sim': 1.0},
 {'u2.user_name': 'altmer', 'sim': 1.0},
 {'u2.user_name': 'rajeshmeniya', 'sim': 1.0}]

In [105]:
start = time.time()

repo_id = 843222
threshold = 1

# Find similar repos

query = (### Similarity normalization : count number of repos starred by u1 ###
  # Count movies rated by u1 as countm
  'MATCH (u1:`User`)-[:`WatchEvent`]->(r1:`Repo` {repo_id: {repo_id}}) '
  'WITH count(u1) as count1 '
  ### Score normalization : count number of users who are considered similar to u1 ###
  # Retrieve all users u2 who share at least one starred repo with u1
  'MATCH (u1:`User`)-[:`WatchEvent`]->(r1:`Repo` {repo_id: {repo_id}}) '
  'MATCH (r2:`Repo`)<-[w:`WatchEvent`]-(u1) '
  'WHERE NOT r1=r2 '
  # Compute similarity
#   'WITH r2, count1, tofloat(count(w)) / count1 as sim '
  'WITH r2, count1, tofloat(count(w)) as sim '
  # Keep users u2 whose similarity with u1 is above some threshold
#   'WHERE sim>{threshold} '
  # Compute score and return the list of suggestions ordered by score
  'RETURN DISTINCT r2.repo_name, sim ORDER BY sim DESC ')
  
tx = graph.begin()
result = tx.run(query, {'repo_id': repo_id, 'threshold': threshold}).data()
result

end = time.time()
end-start

0.024912118911743164

In [ ]:
threshold = 0.5

# In Strategy 1, the similarity between two users u1 and u2 is the proportion of starred repos they have in common
# The score of one given movie m is the proportion of users similar to u1 who rated m

query = (### Similarity normalization : count number of repos starred by u1 ###
  # Count movies rated by u1 as countm
  'MATCH (u1:`User` {user_id:{user_id}})-[:`WatchEvent`]->(r1:`Repo`) '
  'WITH count(r1) as count1 '
  ### Score normalization : count number of users who are considered similar to u1 ###
  # Retrieve all users u2 who share at least one starred repo with u1
  'MATCH (u1:`User` {user_id:{user_id}})-[:`WatchEvent`]->(r1:`Repo`) '
  'MATCH (r1)<-[w:`WatchEvent`]-(u2:`User`) '
  'WHERE NOT u2=u1 '
  # Compute similarity
  'WITH u2, count1, tofloat(count(w))/count1 as sim '
  # Keep users u2 whose similarity with u1 is above some threshold
  'WHERE sim>{threshold} '
  # Count number of similar users as countu
  'WITH count(u2) as count2, count1 '
  ### Recommendation ###
  # Retrieve all users u2 who share at least one movie with u1
  'MATCH (u1:`User` {user_id:{user_id}})-[:`Has_rated`]->(m1:`Movie`) '
  'MATCH (m1)<-[r:`Has_rated`]-(u2:`User`) '
  'WHERE NOT u2=u1 '
  # Compute similarity
  'WITH u1, u2,countu, tofloat(count(r))/countm as sim '
  # Keep users u2 whose similarity with u1 is above some threshold
  'WHERE sim>{threshold} '
  # Retrieve movies m that were rated by at least one similar user, but not by u1
  'MATCH (m:`Movie`)<-[r:`Has_rated`]-(u2) '
  'WHERE NOT (m)<-[:`Has_rated`]-(u1) '
  # Compute score and return the list of suggestions ordered by score
  'RETURN DISTINCT m, tofloat(count(r))/countu as score ORDER BY score DESC ')
tx = graph.cypher.begin()
tx.append(query, {'user_id': user_id, 'threshold': threshold})
result = tx.commit()